// src/app/features/alerts/alert-queue/alert-queue.component.ts
import { Component, computed, inject, OnInit, signal } from '@angular/core';
import { AlertService } from '../../../core/services/alert.service';
import type { AlertSeverity } from '../../../core/models/alert.model';
import { BadgeComponent } from '../../../shared/components/badge/badge.component';
import { EmptyStateComponent } from '../../../shared/components/empty-state/empty-state.component';
import { TimeAgoPipe } from '../../../shared/pipes/time-ago.pipe';

type SeverityFilter = 'ALL' | AlertSeverity;

@Component({
  selector: 'app-alert-queue',
  standalone: true,
  imports: [BadgeComponent, EmptyStateComponent, TimeAgoPipe],
  template: `
    <div class="page-header">
      <div>
        <h2 class="page-title">Alert Queue</h2>
        <p class="text-sm fp-text-secondary">Fraud alerts generated by the decision engine.</p>
      </div>
    </div>

    @if (error()) {
      <div class="card mb-4 border border-red-200 bg-red-50 text-sm text-red-700">{{ error() }}</div>
    }

    <!-- Summary bar + severity filter -->
    <div class="card mb-4">
      <div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">

        <!-- Severity filter tabs -->
        <div class="inline-flex rounded-sm border border-[var(--fp-border)] p-1" style="background-color: var(--fp-surface)">
          @for (sev of severities; track sev) {
            <button
              type="button"
              class="px-3 py-1.5 rounded-sm text-sm font-medium"
              [class.fp-tab-active]="severityFilter() === sev"
              [class.fp-text-secondary]="severityFilter() !== sev"
              (click)="severityFilter.set(sev)"
            >
              {{ sev }}
            </button>
          }
        </div>

        <!-- Live counts -->
        <div class="flex flex-wrap items-center gap-3 text-sm">
          <span class="badge-high">{{ counts().HIGH }} HIGH</span>
          <span class="badge-medium">{{ counts().MEDIUM }} MEDIUM</span>
          <span class="badge-low">{{ counts().LOW }} LOW</span>
        </div>

      </div>
    </div>

    <!-- Alert table -->
    <div class="card overflow-hidden">
      @if (loading()) {
        <p class="p-6 text-sm fp-text-secondary">Loading alerts…</p>
      } @else if (filtered().length === 0) {
        <app-empty-state icon="Done" message="No alerts found" />
      } @else {
        <div class="overflow-auto">
          <table class="fp-table">
            <thead>
              <tr>
                <th>Age</th>
                <th>Alert ID</th>
                <th>Transaction</th>
                <th>Reason</th>
                <th>Severity</th>
              </tr>
            </thead>
            <tbody>
              @for (alert of filtered(); track alert.id) {
                <tr>
                  <td>{{ alert.createdAt | timeAgo }}</td>
                  <td><span class="fp-data-mono">{{ alert.id }}</span></td>
                  <td><span class="fp-data-mono">{{ alert.transactionId }}</span></td>
                  <td class="max-w-md">{{ alert.reason }}</td>
                  <td><app-badge [value]="alert.severity" /></td>
                </tr>
              }
            </tbody>
          </table>
        </div>
      }
    </div>
  `,
})
export class AlertQueueComponent implements OnInit {
  private alertService = inject(AlertService);

  severities: SeverityFilter[] = ['ALL', 'HIGH', 'MEDIUM', 'LOW'];
  severityFilter = signal<SeverityFilter>('ALL');

  readonly loading = this.alertService.loading;
  readonly error = this.alertService.error;

  // All alerts from the service
  private allAlerts = this.alertService.alerts;

  // Filtered by selected severity
  filtered = computed(() => {
    const filter = this.severityFilter();
    const alerts = this.allAlerts();
    return filter === 'ALL'
      ? alerts
      : alerts.filter(a => a.severity === filter);
  });

  // Counts across all alerts regardless of filter
  counts = this.alertService.countBySeverity;

  ngOnInit(): void {
    this.alertService.load();
  }
}